name: 'Commit Count'
description: 'Github action to enforce naming convention on branch names'
author: 'pax217'
inputs:
  except-branches:  # id of input
    description: 'Excepted target branches (possible to pass multiple branches separated by ;)'
    required: false
  commits-count:  # id of input
    description: 'Possible count of commits'
    required: false
    default: 1
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'alert-triangle'
  color: 'gray-dark'
